name: NormalizInterface
version: 0.3
date: 15/05/2015
description: GAP wrapper for normaliz

authors:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Max Horn
      url: http://www.quendi.de/math
    - name: Christof Söger
      url: http://www.math.uos.de/normaliz

maintainers:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Max Horn
      url: http://www.quendi.de/math
    - name: Christof Söger
      url: http://www.math.uos.de/normaliz

GAP: ">= 4.7"

www: https://github.com/gap-packages/NormalizInterface
readme: https://github.com/gap-packages/NormalizInterfaceREADME
packageinfo: https://github.com/gap-packages/NormalizInterfacePackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/NormalizInterface/releases/download/v0.3/NormalizInterface-0.3.tar.gz
    - name: tar.bz2
      url: https://github.com/gap-packages/NormalizInterface/releases/download/v0.3/NormalizInterface-0.3tar.bz2

abstract: The NormalizInterface Package ... TODO

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
