name: NormalizInterface
version: 0.1dev
date: ??/03/2014
description: GAP wrapper for normaliz

authors:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Max Horn
      url: http://www.quendi.de/math
    - name: Christof Söger
      url: mailto:csoeger@uos.de

maintainers:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Max Horn
      url: http://www.quendi.de/math
    - name: Christof Söger
      url: mailto:csoeger@uos.de

GAP: ">= 4.7"

www: https://github.com/fingolfin/NormalizInterface
readme: https://github.com/fingolfin/NormalizInterfaceREADME
packageinfo: https://github.com/fingolfin/NormalizInterfacePackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/fingolfin/NormalizInterfaceNormalizInterface-0.1dev.tar.gz
    - name: tar.bz2
      url: https://github.com/fingolfin/NormalizInterfaceNormalizInterface-0.1devtar.bz2

abstract: The NormalizInterface Package ... TODO

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
